version: v1beta9
images:
  remote:
    image: gcr.io/djw-ai/services/neurafuse/develop/pytorch/tpu:latest
dev:
  sync:
  - imageName: remote
    namespace: neurafuse-djw
    localSubPath: ../lightning-py
    containerPath: /app/lightning-py
    excludePaths:
      - ../lightning-py/pytorch/data