version: v1beta9
images:
  remote:
    image: gcr.io/djw-ai/services/neurafuse/develop/remote/pytorch/tpu:latest
dev:
  sync:
  - imageName: remote
    namespace: neurafuse-djw
    localSubPath: ../lightning
    containerPath: /app/lightning
    excludePaths:
      - ../lightning/pytorch/data